// app/layout.tsx
import '../styles/globals.css';
import { Geist } from 'next/font/google';
import { Roboto_Slab, Inter } from 'next/font/google'; 

const robotoSlab = Roboto_Slab({
  subsets: ['latin'],
  weight: ['700'],
  display: 'swap',
});

const geist = Geist({
  subsets: ['latin'],
  variable: '--font-geist',
});

const inter = Inter({ subsets: ['latin'], display: 'swap' }); 

export const metadata = {
  title: 'AI MED RANKING',
  description: 'Generated by create next app',
  icons: {
    icon: '/favicon.ico', 
  }
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${geist.variable} ${inter.className} antialiased`}> 
        <main className="scrollbar-hide px-4 max-w-7xl mx-auto pt-20">
          {children}
        </main>
      </body>
    </html>
  );
}
